### ISSUE TITLE
Streams for file downloads

### ISSUE THREAD

**Issue by tsabolov** [contextio/ContextIO-node#14]
Do you plan to add support for Streams in `files/:file_id/content` endpoint? I am using GridFS for storing files on my side, and it would be more convenient to have a ReadStream in `client.accounts(:account_id).files(:file_id).content()`.

**Comment by tsabolov** [comment]
I just realized that I can get a file URL requesting a `files/:file_id/content` endpoint with `as_link` parameter then request a file content with a tool of my choice, including a `http(s).request` which will give me a Stream instance.
Sorry for disturbing.

**Comment by tonyblank** [comment]
No worries! Always appreciate feedback on our client libraries. Have a great day.
