### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by AdriVanHoudt** [contextio/ContextIO-node#15]
```javascript
Debug: internal, implementation, error 
    SyntaxError: Uncaught error: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/.../node_modules/contextio/lib/ContextIO.js:186:26)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:492:13)
````

**Comment by rltvty** [comment]
@AdriVanHoudt Do you know which calls you are making to our API when this error occurs?

**Comment by AdriVanHoudt** [comment]
I think mainly webhooks (2.0)

**Comment by rltvty** [comment]
@AdriVanHoudt POST to webhooks (2.0) or GET list?

**Comment by AdriVanHoudt** [comment]
ContextIO posting webhook to our server, can also be an issue in node
library

**Comment by AdriVanHoudt** [comment]
Any progress on this? @rltvty

**Comment by AaronLaBrie** [comment]
@AdriVanHoudt We've released a new version of this library that will be supported going forward. Sorry for the delay, check out the README for more info!

**Comment by AdriVanHoudt** [comment]
Was this issue specifically addressed? And if so yes?
Also did you just rewrite the whole module? :astonished: 
And since the new version seems to only support promises now I would have to rewrite everything which I do not want to do to just fix this issue...

**Comment by AaronLaBrie** [comment]
I've been unable to reproduce the issue in the new version, and we've made significant improvements to our webhooks in the last several months. I'd encourage you to give it a shot and see how it works for you. 

Yes, I did entirely rewrite the library and there are breaking changes. The old version was extremely difficult to work in. 

If you'd like, I could write up a snippet showing how to migrate your code from previous versions to the new beta client.

**Comment by AdriVanHoudt** [comment]
Trust there is nothing more that I like then new versions of modules ^^ 
But having to rewrite everything where I use the module would take too much time atm.
(Also I am more in favor of callbacks and I don't mind modules supporting the 2 but that is a whole other discussion ;) )

I don't think a snippet is needed, unless there are more changes then just the promises that I missed?

**Comment by AaronLaBrie** [comment]
Resources such as `connect_tokens` are no longer aliased to `connectTokens, and specifying a which version of the client to use is slightly different. But it still defaults to 2.0.

**Comment by AdriVanHoudt** [comment]
Hmm yeah I don't expect to much problems then upgrading, what is the plan to go out of beta?

**Comment by AaronLaBrie** [comment]
We have some plucky volunteers working the new version into their apps right now, and I think we'll get some good feedback out of that. 

If I had to guess I'd say we could drop the beta tag by the end of the month, but we'll see what kind of commentary we get back.

After this conversation though, I think I am going to add a "What's changed?" section to the README. Could be useful.

**Comment by AdriVanHoudt** [comment]
Ok I will probably make the change when it is out of beta then. And yeah that could be handy.

**Comment by AaronLaBrie** [comment]
The README has been updated :+1:

**Comment by AdriVanHoudt** [comment]
:+1:
