### ISSUE TITLE
Method messages() doesn't exist in sources

### ISSUE THREAD

**Issue by mjyoung** [contextio/ContextIO-node#16]
I get no such method messages() when trying to run:

```javascript
ctxioClient.accounts(accountId).sources(label).folders(folder).messages().get(req.query, function (err, response) {
  if (err) throw err;
  return res.json(response.body);
});
```

This is for the endpoint:
`https://api.context.io/2.0/accounts/id/sources/label/folders/folder/messages`

Looking at ContextIO.js under the `sources() -> folders()` function, I see methods for `get`, `post`, `delete`, and `expunge`, but no `messages` method.

**Comment by mjyoung** [comment]
This should be fixed in pull request:
https://github.com/contextio/ContextIO-node/pull/17

**Comment by AaronLaBrie** [comment]
@mjyoung We've released a new version of this library that will be supported going forward. Thanks so much for opening PR's, I'm sorry that they never got checked out.
