### ISSUE TITLE
Does not support POST /messages/<messageID>/folders with type array value for "add" or "remove" keys

### ISSUE THREAD

**Issue by trever** [contextio/ContextIO-node#18]
There is an inconsistency with how the OAuth.js file and querystring package format URLs, causing a signature error on the baseURL.

Querystring natively separates out the array into duplicate key/value pairs, eg: ```&add=Today&add=Tomorrow```

OAuth.js has a bug which strips any values beside the first in the array, eg: ```&add=Today```

Context.IO API requires each element in the array to be broken out into a separate key/value pair, with square brackets before the equal sign, eg: ```&add[]=Today&add[]=Tomorrow```

I'll submit a PR for the fix to OAuth.js and to Querystring, but I'm not sure querystring's implementation of array stringification is incorrect, so they might decide to not support the bracketing convention. 

Thoughts? It seems both redundant and inefficient to have URL formatting functions in OAuth.js and to use the querystring package to achieve the same job, especially since the server is comparing the URL with its signed counterpart.

**Comment by trever** [comment]
Any update on this?

**Comment by AaronLaBrie** [comment]
@trever We've released a new version of this library that will be supported going forward. 

I'm sorry that your PR's never got reviewed :(
