### ISSUE TITLE
Gmail oAuth: Cannot bypass intermediate steps.

### ISSUE THREAD

**Issue by oozzal** [contextio/ContextIO-node#23]
While creating `connect_token` and obtaining oAuth2 token for Gmail, contextIO has these two intermediate steps where it asks to:
* enter `first_name` `last_name` and `email`
* sure we are signed in.

I'm able to skip the second step by making a post request to `https://api.context.io/connect/<TOKEN_ID>` with `next=oauth` and following the redirect url which takes to Google Authorization page, but **NOT** the first one.

My application uses Gmail only oAuth and I need to skip both of the above steps which are redundant when my end user knows he/she's connecting his Gmail with my application.

**Comment by cecyc** [comment]
We've made a change to allow for this functionality. If you append `skip_oauth_splash=1` as a parameter to the `browser_redirect_url` you get when creating a connect token, you will now skip directly to the gmail authentication screen.

Thanks for the suggestion!
