### ISSUE TITLE
Add new user to get all the contacts

### ISSUE THREAD

**Issue by abdulbarik** [contextio/ContextIO-node#32]
Can we add new user and fetch all the contacts of newly added user with node.js library?

**Comment by AaronLaBrie** [comment]
Absolutely! 

The account creation call would look something like:
 `ctxioClient.accounts().post({ ... }).then(...)` 

The response from which will have an id that you could then use to make calls like:
`ctxioClient.accounts(id).contacts().get().then(...)` 

Check out our [docs](https://context.io/docs/2.0/accounts#post) for more info.

**Comment by abdulbarik** [comment]
Yeah I tried it but it doesn't seems to work. I get account ID but when I use it I get this error
"This account has no mailboxes. API calls on it won't return any data.".
Mean the I have to grant permission from source like ("Gmail", "Outlook") etc, after that I can fetch the contacts.
I think Context.io using Oauth1.0 and I am getting status code "401" while requesting from "request.js" module.  
I am getting this result while fetching contacts 
{
  "query": {
    "limit": 25, 
    "offset": null, 
    "active_after": null, 
    "active_before": null, 
    "search": null
  }, 
  "matches": [ ]
}
I can use your REST APIs or node module. Please give me a proper solution so that I can get it done.

**Comment by cecyc** [comment]
@abdulbarik it sounds like you need to connect a mailbox to the account. Could you please send a support request to support@context.io with the account id of the account giving you trouble so we can take a look and see what's happening? Thanks!
