### ISSUE TITLE
GET connect_token - returning entire list?

### ISSUE THREAD

**Issue by bryce-h** [contextio/ContextIO-node#39]
Hi, 

Has anyone experienced this before, I running the get required after a user has created an account, to retrieve the information on the token and get account information to associate with user.
I run the query and it returns the entire list of connect_tokens, with the last one being the most recent and token I am looking for.

Here is my current function, where id is equal to the id of the token I am looking for
```js
return ctxioClient.connect_tokens().get({ token: id }).then( function (res) {
      return res
    } ).catch( function (err) {
      console.log('err', err.message)
    });
```
<img width="694" alt="screen shot 2017-02-01 at 7 12 16 pm" src="https://cloud.githubusercontent.com/assets/20308667/22535804/62c402da-e8b2-11e6-9ec5-16e97a15fd62.png">
This image is the end of the response I am receiving, and the rest is a long list of past tokens

**Comment by AaronLaBrie** [comment]
Hey @bryce-h, this one should be an easy fix.
All you have to do is move the `id` to the `connect_tokens` part of you call, like so:

```
return ctxioClient.connect_tokens(id).get().then( function (res) {
  return res
})
```

Let me know if that does it for you.

**Comment by bryce-h** [comment]
@AaronLaBrie haha, I'm ashamed it was that easy. Works flawlessly. Thanks a lot for your help!

**Comment by AaronLaBrie** [comment]
No worries! Let us know if you have any other questions.
