### ISSUE TITLE
 Cannot read property 'slice' of undefined at at sendRequest.then.res (node_modules/contextio/lib/call-service.js:71:74

### ISSUE THREAD

**Issue by VeereshDigasangi** [contextio/ContextIO-node#47]
Hi,
I'm not able call the **getFile** call to download the attachments.
This is the stacktrace from node module 
 **Cannot read property 'slice' of undefined
    at sendRequest.then.res (/home/veeresh/FlowRepo/newflow/backend/backend-services/engine/node_modules/contextio/lib/call-service.js:71:74)
From previous event:
    at Request.RP$exposed [as then] (/home/veeresh/FlowRepo/newflow/backend/backend-services/engine/node_modules/request-promise-core/lib/plumbing.js:145:61)
    at Object.getFile (/home/veeresh/FlowRepo/newflow/backend/backend-services/engine/node_modules/contextio/lib/call-service.js:70:40)**

FYI,
I go through the call-service.js file in line number 70 there is a method called slice on the headers object  content-disposition, this field have no values that's why the code was broken.
here is the line:  _const filename = res.headers['content-disposition'].split('=')[1].slice(1, -1);_

As per your guidance I'm trying to use getFile method but this is also throwing an error, you guys are not handling errors and there is not at all try-catch block and there is no proper testing on the module and no proper documentation for the API how to use? what to pass in request , etc.
Here is the link for my last issue and it was closed without solving the issue.
https://github.com/contextio/ContextIO-node/issues/46

My code for reference:
```
 const ctxioClient = ContextIO({
    key: input.connection.consumer_key,
    secret: input.connection.consumer_secret
  })
//I tried both methods: get and getFile both are not working, end up with library issues.
 ctxioClient.users(input.id).email_accounts(input.label).folders(input.folder).messages(input.message_id).attachments(input.attachment_id).getFile().then(res => {
     console.log(res);
  }).catch(err => {
    console.log(err)
  })

```

**Comment by AaronLaBrie** [comment]
The filename should be passed in that header, but IMAP doesn't always provide that header for us to use. We'll just return an empty string `''` from now on if it's missing.

I've added a check for that missing header, updated the readme, and cut a new release (v1.3.1).

In regards to 'proper testing': as you can see in the [Readme](https://github.com/contextio/ContextIO-node/blob/master/README.md#testingdebugging) and the [spec folder](https://github.com/contextio/ContextIO-node/tree/master/spec), this library is tested. If you are unsatisfied with the testing here, feel free to add some in a pull request!
