### ISSUE TITLE
 400 - "{\"type\":\"error\",\"value\":\"new_folder_id is required\"}"

### ISSUE THREAD

**Issue by VeereshDigasangi** [contextio/ContextIO-node#48]
Hi,
I'm trying to move message from one folder to another folder, in developer API console it is working properly but using node module it's not working even though the passing of all required parameters.
I'm running lite version which is default version.
Find the below code, I'm passing **new_folder_id** but still node_module throwing '**new_folder_id**' is required and you can see the consoles over there.

```
var ContextIO = require('contextio');
    const ctxioClient = ContextIO({
      key: input.connection.consumer_key,
      secret: input.connection.consumer_secret
    })
    var params = {
      "new_folder_id": input.folder_id
    };
    console.log(params); // { new_folder_id: 'NEW_1' }
    ctxioClient.users(input.id).email_accounts(input.label).folders(input.folder).messages(input.message_id).put(params).then(res => {
      return output(null, res);
    }).catch(err => {
    console.log(err)
    })
```

**Comment by AaronLaBrie** [comment]
I'm able to recreate this one too, I'll do some digging and update here when I find a solution. Thanks!

**Comment by AaronLaBrie** [comment]
Realized what the problem is: [this endpoint](https://docs.context.io/#moving-messages) is expecting query params, not body params. Just change that to `.put(null, params)` and you should be good to go [(relevant bit from the readme)](https://github.com/contextio/ContextIO-node#parameters).

**Comment by veeresh-dgsg** [comment]
@AaronLaBrie  How it will be REST api call, I'm trying to send new_folder_id in body and json or qs,formData but it is not working. Can I have the simple format to know how I can pass new_folder_id.
Hope it will help a lot..

**Comment by AaronLaBrie** [comment]
As mentioned above, you should just have to change the end of that call from `.put(params)` to `.put(null, params)`. Have you done so?

**Comment by VeereshDigasangi** [comment]
I'm not using npm module, I'm trying http put call. Rest API call.

**Comment by cecyc** [comment]
@VeereshDigasangi Please keep all questions related to this library.

If you need resources regarding the REST endpoints, please refer to our REST API documentation here: https://docs.context.io
