### ISSUE TITLE
copying non-own-property issue

### ISSUE THREAD

**Issue by abstractmatter** [contextio/ContextIO-node#8]
Hy there,

Are you Okay to switch from:

for (var i in tmp) {
   tmp[i].copy(buf, length);
   length += tmp[i].length;
}

To:

for (var i in tmp) {
  if (tmp.hasOwnProperty(i)) {
    tmp[i].copy(buf, length);
    length += tmp[i].length;
  }
}

To avoid errors when objects/functions are extended?

Thanks,

François

**Comment by sushithegreat** [comment]
Merged, thanks!
